services:
  go-poc:
    build:
      context: ./go-poc
    volumes:
      - ./fixtures/sample_001.parquet:/fixtures/sample_001.parquet
      - ./results:/results
    environment:
      WRITE_RESULT_PARQUET: false
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500m  # 500 megabytes

  python-poc:
    build:
      context: ./python-poc
    volumes:
      - ./fixtures/sample_001.parquet:/fixtures/sample_001.parquet
      - ./results:/results
    environment:
      WRITE_RESULT_PARQUET: false
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500m  # 500 megabytes

  node-poc:
    build:
      context: ./node-poc
    volumes:
      - ./fixtures/sample_001.parquet:/fixtures/sample_001.parquet
      - ./results:/results
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1536m  # 1.5 gb, with less the container is OOM killed


  rust-poc:
    build:
      context: ./rust-poc
    volumes:
      - ./fixtures/sample_001.parquet:/fixtures/sample_001.parquet
      - ./results:/results
    environment:
      WRITE_RESULT_PARQUET: false
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500m  # 500 megabytes
